version: '3'
services:
  web:
    stdin_open: true

    build:
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "3000:3000"

    volumes:
      - /app/node_modules
      - /c/Puneet/Code/frontend:/app

    environment:
       - CHOKIDAR_USEPOLLING=true

  tests:
    stdin_open: true

    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - /c/Puneet/Code/frontend:/app
    command: ["npm","run","test"]